<?php

namespace App\Constants;

class GlobalConstant
{
    const CATEGORIES = [
        "American",
        "Cajun",
        "Bagels",
        "Sandwiches",
        "Italian",
        "Asian",
        "Salad",
        "Indian",
        "French",
        "Vietnamese",
        "Mexican",
        "Thai",
        "Tapas",
        "Chinese",
        "Pizza",
        "Mediterranean",
        "Caribbean",
        "English",
        "Coffee",
        "Californian",
        "Sushi",
        "Vegan"
    ];

    const RESTAURANT = [
        "Cheesecake Factory",
        "Shokolaat",
        "Gordon Biersch",
        "Crepevine",
        "Creamery",
        "Old Pro",
        "Nola's",
        "House of Bagels",
        "The Prolific Oven",
        "La Strada",
        "Buca di Beppo",
        "Pasta?",
        "Madame Tam",
        "Sprout Cafe",
        "Pluto's",
        "Junoon",
        "Bistro Maxine",
        "Three Seasons",
        "Sancho's Taquira",
        "Reposado",
        "Siam Royal",
        "Krung Siam",
        "Thaiphoon",
        "Tamarine",
        "Joya",
        "Jing Jing",
        "Patxi's Pizza",
        "Evvia Estiatorio",
        "Cafe 220",
        "Cafe Renaissance",
        "Kan Zeman",
        "Gyros-Gyros",
        "Mango Caribbean Cafe",
        "Coconuts Caribbean Restaurant & Bar",
        "Rose & Crown",
        "Baklava",
        "Mandarin Gourmet",
        "Bangkok Cuisine",
        "Darbar Indian Cuisine",
        "Mantra",
        "Janta",
        "Hyderabad House",
        "Starbucks",
        "Peet's Coffee",
        "Coupa Cafe",
        "Lytton Coffee Company",
        "Il Fornaio",
        "Lavanda",
        "MacArthur Park",
        "St Michael's Alley",
        "Osteria",
        "Vero",
        "Cafe Renzo",
        "Miyake",
        "Sushi Tomo",
        "Kanpai",
        "Pizza My Heart",
        "New York Pizza",
        "California Pizza Kitchen",
        "Round Table",
        "Loving Hut",
        "Garden Fresh",
        "Cafe Epi",
        "Tai Pan"
    ];

    const STATUS = ['open', 'closed'];
}
